### ISSUE TITLE
`CryptoPunks.json` is missing last 1000 punks

### ISSUE THREAD

**Issue by krzysu** [muditmarda/CryptoPunk#1]
Where did you get `CryptoPunks.json` from? It is missing the last 1000 punks. I'm looking for a source of all punks with attributes and any help would be appreciated.

**Comment by dariusdev** [comment]
Also other types are missing: like Alien : https://www.larvalabs.com/cryptopunks/attributes

**Comment by krzysu** [comment]
I don't need it anymore and I didn't get any answer here so I'm closing it
